# Citrusleaf Foundation
# Makefile

DEPTH = ../../..
include Makefile.in
include Makefile.files

DIR_INCLUDE = ../include $(DEPTH)/include

DIR_OBJECT = ../obj/x64
DIR_TARGET = ../lib64

TARGET = keyTest

INCLUDES = $(DIR_INCLUDE:%=-I%) 
LIBRARIES = -lcitrusleaf  -lssl -lpthread -lrt
LDFLAGS += -L$(DEPTH)/lib64

OBJECTS = $(SOURCES:%.c=$(DIR_OBJECT)/%.o)
DEPENDENCIES = $(OBJECTS:%.o=%.d)

.PHONY: all
all: keyTest


.PHONY: clean
clean:
	/bin/rm -r -f $(OBJECTS) $(DIR_TARGET)/$(TARGET_S) $(DIR_TARGET)/$(TARGET_D)

.PHONY: depclean
depclean: clean
	/bin/rm -f $(DEPENDENCIES)

.PHONY: keyTest
keyTest: $(OBJECTS)
	mkdir -p $(DIR_TARGET)
ifeq (${MARCH_NATIVE},x86_64)
	$(CC) $(LDFLAGS) -o $(DIR_TARGET)/$(TARGET) $(OBJECTS) $(LIBRARIES)
endif

-include $(DEPENDENCIES)

$(DIR_OBJECT)/%.o: %.c
	mkdir -p $(DIR_OBJECT)
	$(CC) $(CFLAGS_64) -fPIC -MMD -o $@ -c $(INCLUDES) $<
